# Per-email metadata. Dates are ESTIMATES inferred from clues in the text (no send dates in the archive).
# yt = YouTube potential 1-5. fmt = email format. vid = suggested video format.
M = {
1: dict(date="Oct–Nov 2025", conf="High", basis="Aroha 'turns 17 next week'; born ~Oct/Nov 2008 ('10K a month by end of October… a few weeks before she arrives').",
   fmt=["Origin story"], topics=["Goals & deadlines","Money","Origin"],
   idea="A dollar amount and a deadline beat waiting for someone to save you.",
   assets="$60K/yr income, ~$30K left for a family of 5; $10K/month target; hit it weeks before Aroha was born; 17-year callback.",
   yt=5, vid="Story-led long-form (8–12 min) + 60s Short of the 'I'm pregnant' moment",
   title="I Was Broke With a Baby on the Way. One Number Saved Us.",
   hook="A mate slipped me $200 so I could buy groceries. I got home and my wife said, 'I'm pregnant.'"),
2: dict(date="2025–26", conf="Low", basis="Recent event recap ('last month'); Jay's PE sale 'last year'.",
   fmt=["Event recap","Case study (x2)"], topics=["Business design","Scale vs lifestyle"],
   idea="It's not scale vs lifestyle. It's design vs default. Not choosing is what kills you.",
   assets="Jay: $7K/mo → $3M/mo, 1,000+ clients, part-sold to PE. Rob: $5.8M/yr, 85% profit, team of 5, 320 hrs/yr, backyard golf course.",
   yt=5, vid="Versus / debate: restage Jay vs Rob on camera, or a split-screen explainer",
   title="$3M/Month Empire vs $5.8M Lifestyle Business: Which Should You Build?",
   hook="One of them works 320 hours a year. The other sold to private equity."),
3: dict(date="2025–26", conf="Medium", basis="Email shame '2 years ago'; Salesless '5x'd our business in the last 12 months'.",
   fmt=["Philosophy","Confession"], topics=["Decision-making","Standards","Salesless origin"],
   idea="Navigate by pride and shame, not just metrics. Shame gets you moving; pride stops you settling.",
   assets="Refunded $38K to 380 workshop attendees; $60K/mo ads + 9 salespeople yet flat; Simpsons 'Less shame?' clip.",
   yt=4, vid="Talking-head essay; the $38K refund works as a standalone Short",
   title="Why I Refunded $38,000 Nobody Asked For",
   hook="380 people paid. Nobody complained. I gave every dollar back the same day."),
4: dict(date="2024–25", conf="Low", basis="Evergreen; '650+ coaches hit $1M', '8-figure business'.",
   fmt=["Manifesto","Self-deprecating story"], topics=["Strengths","ADHD","Positioning"],
   idea="Stop fixing weaknesses. Take a 7 or 8 strength up to an 11. That's where the money is.",
   assets="Game character-point analogy; 3 conferences, same day, 3 continents; read-only calendar access.",
   yt=5, vid="Essay with character-builder graphics; calendar incident as a Short. Book-title video.",
   title="I Feel Sorry for the Normies (Stop Working on Your Weaknesses)",
   hook="My team banned me from my own calendar. I've got read-only access now. After the incident."),
5: dict(date="2025–26", conf="Low", basis="Salesless-era language (offer doc → apply → buy).",
   fmt=["Contrarian framework"], topics=["Marketing","Funnels","Cold/Warm/Hot"],
   idea="Funnels are built for unicorns. Real buyers move through a web. Design Cold → Warm → Hot invitations.",
   assets="Hand-drawn kraft card: FUNNEL (struck out) vs WEB; stage-by-stage asset list.",
   yt=5, vid="Brown-paper whiteboard explainer (10 min)",
   title="The Funnel Is Dead. Build a Web Instead.",
   hook="Your funnel was designed for a customer who doesn't exist."),
6: dict(date="Jul–Aug 2026", conf="Medium", basis="Written during Kiri-Maree's chemo (same season as #49).",
   fmt=["Confession","Update"], topics=["Email","Founder voice","Taking back control"],
   idea="If your list is dead, you killed it. Would you read your own emails?",
   assets="Ghost-written 'homeopathic' emails; chain reaction: email → IG → YouTube → Salesless; 36 → 8 team; 5x sales.",
   yt=4, vid="Talking-head story; one-question challenge format",
   title="Your Email List Isn't Dead. You Killed It.",
   hook="I realised I wouldn't read my own emails. That one admission changed everything."),
7: dict(date="~Feb 2026", conf="High", basis="'No sales team since Christmas 2024… about 14 months ago'.",
   fmt=["Results update","Philosophy"], topics=["Salesless","Founder-led marketing","Marketing vs sales"],
   idea="Sales problems are marketing problems handled downstream. Move persuasion upstream into content.",
   assets="9-person sales team removed; team 36 → 8.5; ads $60K → $6K/mo; 5x in a year; Black Belt sold out 8 months; 120 on Boardroom waitlist; Naval quote.",
   yt=5, vid="Pillar long-form (12–15 min): the decision, the fear, the numbers",
   title="I Fired My Entire Sales Team. We Grew 5x.",
   hook="We haven't had a single salesperson since Christmas 2024, and we're never going back."),
8: dict(date="2025", conf="Low", basis="'Last year, I worked with… Sharran'.",
   fmt=["Client case study","Data insight"], topics=["Nurture","Brandwidth","Conversion speed"],
   idea="Time on brand, not time on list. Get new leads to 47 minutes of content fast. Bingers are buyers.",
   assets="Sharran's buyer study: every buyer consumed 47+ min; time-to-client halved.",
   yt=4, vid="Data explainer + Short ('the 47-minute rule')",
   title="The 47-Minute Rule: Why Bingers Become Buyers",
   hook="Every single buyer had one thing in common, and it wasn't how long they'd been on the list."),
9: dict(date="2025–26", conf="Low", basis="Curated viral dating-app story.",
   fmt=["Borrowed story + commentary"], topics=["Demand","Scarcity","Pricing power"],
   idea="Scarcity makes you chase; demand lets you choose. Your problem isn't mindset. It's volume.",
   assets="Hinge experiment: 1,500+ likes in 24 hrs. Most of the email is someone else's words.",
   yt=3, vid="Commentary/react segment. Retitle; credit the original creator.",
   title="Why You're Chasing Clients (A Dating-App Experiment Explains It)",
   hook="A guy made a dating profile as a woman. What happened explains your sales pipeline.",
   flag="The email title isn't safe for a YouTube title/thumbnail. The story is borrowed, so credit it."),
10: dict(date="Late 2025", conf="Medium", basis="'Only 15k subscribers'. In Nov 2025 DMs (#16) Taki says he's '9 months in' on YouTube.",
   fmt=["Philosophy","Framework (3 steps)"], topics=["Contrarian positioning","Attention"],
   idea="Find the common advice (the window) and throw your better new way (the brick) through it.",
   assets="Peer quote on why Taki's YouTube works; 6 old-way vs new-way pairs; 3-step exercise.",
   yt=5, vid="Framework explainer; old-vs-new list makes great on-screen graphics",
   title="How to Get Attention in a Crowded Market: Throw a Brick",
   hook="'How is Taki Moore getting thousands of views with only 15K subscribers?' Here's the answer."),
11: dict(date="2025–26", conf="Low", basis="AI-content discourse.",
   fmt=["Hot take"], topics=["AI content","Authenticity"],
   idea="'AI writes all my stuff' isn't a flex. We can tell.",
   assets="Aussie 'pinky' anti-speeding ad (RTA).",
   yt=3, vid="Short (≤60s): pinky gesture on camera",
   title="'AI Writes All My Content' Isn't the Flex You Think",
   hook="The best road-safety ad ever made didn't tell anyone to slow down. It embarrassed them."),
12: dict(date="2025–26", conf="Medium", basis="'More than 1,000 clients are doing it'; 9 → 45 sales/month.",
   fmt=["Sales letter","Plan (Doc → Deadline → Demand)"], topics=["Salesless","Sales calls","Offer"],
   idea="Sales calls aren't the answer; they're the friction. People hate being sold but love buying.",
   assets="9 salespeople/9 sales → 0 salespeople/45 sales a month; Rodric $60K/yr → $130K/mo; 3-step method.",
   yt=5, vid="FLAGSHIP pillar video (15–20 min): the Salesless method end-to-end",
   title="Sales Calls Are Killing Your Coaching Business",
   hook="2 no-shows, 1 reschedule, 1 unqualified, and 1 guy who needed to 'ask his wife'."),
13: dict(date="2025", conf="Low", basis="'1,300 people have bought tickets' to workshops so far.",
   fmt=["Experiment/results","Plan"], topics=["Paid workshops","Lead quality"],
   idea="Swap free for paid, webinar for workshop. $100 filters out tire-kickers.",
   assets="5% → 55% qualified overnight; 1,300 attendees, never below 50%; idea → selling in 3 hours.",
   yt=4, vid="Old vs new breakdown with the numbers on screen",
   title="Stop Running Free Webinars (Do This Instead)",
   hook="95% of the people who come to your free webinar will never buy."),
14: dict(date="2025–26", conf="Low", basis="Salesless-era close.",
   fmt=["Personal story (comedy)","Lesson"], topics=["Pressure selling","Retention","Buyer's remorse"],
   idea="Clients who feel sold avoid you like a mugger. They go quiet and leave. Buyers stay.",
   assets="Chandler FILMED the whole thing. Photo of the 3 CDs. $60 Apple Pay shakedown. Hare Krishna flower trick.",
   yt=5, vid="Story-led video cut with Chandler's real footage. High-retention storytelling.",
   title="I Got Scammed on Venice Beach (It Explains Why Your Clients Quit)",
   hook="'You like reggae music?' Fatal mistake."),
15: dict(date="Undated", conf="—", basis="Evergreen thought experiment.",
   fmt=["Thought experiment"], topics=["Offer design"],
   idea="If your offer can't win a nod in total silence, it needs work. A good offer sells itself.",
   assets="Vivid white-room scenario (very visual).",
   yt=4, vid="Staged visual (white room, timer) or animated Short",
   title="Would Your Offer Sell in Complete Silence?",
   hook="5 minutes. One sheet of paper. Nobody's allowed to talk."),
16: dict(date="Early 2026", conf="High", basis="DM screenshots are dated 27–28 Nov 2025, and the email says 'a few months ago'.",
   fmt=["Case study (screenshots)"], topics=["Friction","Buying process","Salesless"],
   idea="You lose sales you can't see because your process won't let people just buy.",
   assets="6 real DM screenshots; $9,995 purchase; 9 → 45 sales/mo ('36 lost sales a month'); a $30–60K sale every 16 hours.",
   yt=5, vid="Screen-share breakdown of the DM thread",
   title="I Tried to Give Him $10K. He Made Me Beg.",
   hook="I asked for the price. Then the link. Then the link again.",
   flag="Blur the seller's identity in the screenshots."),
17: dict(date="Undated", conf="—", basis="Older story ('Years ago'); evergreen.",
   fmt=["Personal story (comedy)"], topics=["Sales hygiene","Hidden objections"],
   idea="People won't tell you the real reason they didn't buy. Find the missing Tic Tac.",
   assets="Photo holding a 50¢ coin; bad-breath PT story.",
   yt=4, vid="Story Short or 5-min story video",
   title="The 50-Cent Fix for Losing Sales",
   hook="He had the perfect sales process. I ran and never went back."),
18: dict(date="2025–26", conf="Medium", basis="'A couple of weeks ago… 1,000 people bought tickets, 45 joined Black Belt'.",
   fmt=["Confession","Philosophy"], topics=["Selling in content","Pitching","Workshops"],
   idea="'Teach then sell' is broken because of the word 'then'. The best content teaches people what to want.",
   assets="1,000-ticket workshop → 45 Black Belt sales with an almost non-existent pitch.",
   yt=5, vid="Breakdown / teardown of the workshop's 'teach what to want' moves",
   title="Why Your Pitch Feels So Awkward (Teach-Then-Sell Is Broken)",
   hook="For years I had Mid-Pitch Puberty."),
19: dict(date="Undated (story 2004)", conf="—", basis="Throwback story from 2004.",
   fmt=["Throwback story","Philosophy"], topics=["Pricing"],
   idea="Your price is written in chalk, not stone. Prospects don't know what it's 'supposed' to be.",
   assets="Secretly added $250/mo to each agreement; $1K → $5K/mo; David never knew.",
   yt=5, vid="Story-led long-form or Short; very thumbnail-able",
   title="I Secretly Raised My Boss's Prices 5x. He Never Knew.",
   hook="Every time he signed a client, I snuck in and changed the price."),
20: dict(date="Undated", conf="—", basis="Early-career story; evergreen.",
   fmt=["Confession","Framework (ROI/COI, 20x)"], topics=["Pricing","Confidence"],
   idea="Your confidence has nothing to do with your value. Price on client ROI and cost of inaction.",
   assets="Adam's '$20 book vs $20K program' line; value = 20x price.",
   yt=4, vid="Talking-head story + simple framework graphic",
   title="Your Confidence Has Nothing to Do With Your Price",
   hook="He gave me his card details, then said, 'Can I give you some feedback? You're too cheap.'"),
21: dict(date="Undated", conf="—", basis="Evergreen.",
   fmt=["Framework (maths)","Plan"], topics=["Pricing","Offer design","Beginners"],
   idea="You're too small to be cheap. The maths lands most coaches at a $2–5K offer.",
   assets="Kraft-paper volume-vs-price log-scale diagram; $100K/yr breakdown.",
   yt=5, vid="Whiteboard maths explainer; great for newer coaches",
   title="You're Too Small to Be Cheap",
   hook="To make $100K you need 100,000 clients at $1… or 10 at $10K."),
22: dict(date="2025", conf="Low", basis="Crash 'a year ago'; Tokyo Boardroom event; Hutto died '2 years ago'.",
   fmt=["Personal story (dramatic)","Lesson"], topics=["Pricing","Bleeding-neck problems","Value"],
   idea="People pay whatever it takes to solve a bleeding-neck problem. Solve a $100K problem for $10K.",
   assets="Land Rover crash + bruise photos; 4 broken ribs, punctured lung; $97K USD medevac flight; the 'Crazy Asian Road Trip'.",
   yt=5, vid="Story-led long-form with photos; strong thumbnail",
   title="I Paid $97,000 for a One-Way Flight to Tokyo",
   hook="The doctor said if I flew, my lungs would collapse and I'd die. I had to be in Tokyo."),
23: dict(date="Undated", conf="—", basis="Evergreen client-of-client story.",
   fmt=["Borrowed story"], topics=["Pricing","Projecting affordability"],
   idea="Don't decide what someone else's 'whatever it takes' is.",
   assets="Pet-motel couple sold all their furniture; 5x'd in 18 months. Jay Abraham quote.",
   yt=4, vid="Short (60–90s) or a segment inside a pricing video",
   title="They Sold Their Furniture to Pay Their Coach",
   hook="He walked in for the first session. The house was empty."),
24: dict(date="2025", conf="Low", basis="Written in Tokyo ('Yesterday'), probably the Boardroom trip.",
   fmt=["Field observation"], topics=["Business model","Free vs premium"],
   idea="Make the cup the lead magnet and sell the beans. Give information freely, charge for implementation.",
   assets="Koffee Mameya: lab coats, 6-pour ritual, 100+ bags of beans a day.",
   yt=3, vid="Travel vlog segment / Short. Best filmed on location.",
   title="This Tokyo Café Sells Coffee Like a Genius",
   hook="The coffee isn't the product."),
25: dict(date="2026", conf="Low", basis="Part of the Onramp/retention run (#25–28).",
   fmt=["Confession","Plan (Onramp)"], topics=["Retention","Onboarding"],
   idea="Heroic saves make great TV and a terrible business model. Design the first 6 weeks.",
   assets="'Heroic Saves' named ritual; the 3 moves: seen, clear, win.",
   yt=4, vid="Talking-head story → framework",
   title="Heroic Saves Are Killing Your Coaching Business",
   hook="'Taki… I just wanted to say thank you…' I knew what was coming."),
26: dict(date="2026", conf="Low", basis="Onramp run.",
   fmt=["Confession","Philosophy"], topics=["Churn","Onboarding"],
   idea="Churn starts at the beginning. Build a program so good people would feel stupid to leave.",
   assets="'If you still had every client who ever joined?' question; belong / believe / breakthrough; Hormozi contrast.",
   yt=4, vid="Emotional open → 3-part framework",
   title="How Big Would Your Business Be If No One Ever Left?",
   hook="A client asked me one question, and I cried."),
27: dict(date="2026", conf="Low", basis="Onramp run; '45 new clients… first Tuesday of every month'.",
   fmt=["Borrowed case study (history)","Framework"], topics=["Onboarding","Customer journey","Moments of Truth"],
   idea="Map the journey, find the Moments of Truth, T-bar each one. 6 of 9 happen in the first 6 weeks.",
   assets="SAS: $17M loss → $54M profit; Moments of Truth + T-bar cards; 45 clients onboarded in 2 hours.",
   yt=5, vid="History story + brown-paper framework (10–12 min)",
   title="I Stole This From an Airline, and It Fixed Our Churn",
   hook="In 1981 a 39-year-old fixed an airline with 2 sheets of paper."),
28: dict(date="2026", conf="Low", basis="'5 years ago, Dan Martell showed me the graph'.",
   fmt=["Case study (own business)","Framework (maths)"], topics=["Churn ceiling","Growth","Onboarding"],
   idea="Ceiling = new clients per month ÷ monthly churn. The fastest way back to growth is fixing onboarding.",
   assets="Churn-ceiling formula; 2 growth-curve cards ('I was here' / 'We are here'); $180K spent getting it right; 4x.",
   yt=5, vid="Whiteboard maths + story. Possible Dan Martell collab/mention.",
   title="The Churn Ceiling: The Math That Predicts When Your Business Flatlines",
   hook="Dan Martell gave us 4 months. That was 5 years ago."),
29: dict(date="2026", conf="Low", basis="Experience-design theme (Onramp run).",
   fmt=["Field observation","Plan"], topics=["Client experience","Word of mouth"],
   idea="Most businesses create Instagram Stories. Great ones create stories people retell.",
   assets="4 photos: hidden entrance, phone lockbox, tallow candle, steak presentation.",
   yt=3, vid="Vlog-style experience walkthrough / Short",
   title="This Restaurant Took Our Phones (Steal This for Your Business)",
   hook="Google Maps led us to a fire exit."),
30: dict(date="Early 2026", conf="Low", basis="'This year I'm excited…'; Janu Tokyo 'a few weeks ago'.",
   fmt=["Micro-observation"], topics=["Client experience","Coaching style"],
   idea="Don't tell and point. Go with people.",
   assets="Janu Tokyo concierge story. Very short email.",
   yt=3, vid="Short (≤45s)",
   title="Don't Tell and Point",
   hook="I asked where the gym was. She didn't tell me."),
31: dict(date="Undated", conf="—", basis="Evergreen family story.",
   fmt=["Family story (comedy)","Philosophy"], topics=["Delivery","Workshops","Do it live"],
   idea="Bad coaches give homework. Good coaches do the work live.",
   assets="Aroha repeating Dad's line to her teacher; call from the principal.",
   yt=4, vid="Story Short + mid-length delivery philosophy video",
   title="Homework Is for Losers (Why Bad Coaches Give Homework)",
   hook="My daughter told her teacher exactly what I'd said. I got a call from the principal."),
32: dict(date="2025–26", conf="Low", basis="'12 months ago this week, she burnt it all down'.",
   fmt=["Client case study"], topics=["Simplification","Business model","Team size"],
   idea="Adopt, then adapt. A business that doesn't fit you can be burned down and rebuilt bigger.",
   assets="Steph: $4K/mo → $1M in 12 months; 120 clients, 80 re-signed for 12 months; team 13 → 4; $2.4M FY; 20 hrs/wk.",
   yt=5, vid="Case-study breakdown, ideally with a Steph interview",
   title="She Burned Down Her $1M Business. Now It Makes $2.4M.",
   hook="She lied on her application to get in.",
   flag="Get Steph's OK before naming her on YouTube."),
33: dict(date="2025–26", conf="Low", basis="Business went '$8M a year, to 20'.",
   fmt=["Anonymised case","Philosophy","Own results"], topics=["Complexity","Cutting","Scale"],
   idea="The secret to scale is scissors. Cut, don't add.",
   assets="Team 36 → 8; ads $60K → $6K/mo; $8M → $20M; 90-day turnaround.",
   yt=5, vid="Essay + own-business numbers; thumbnail: scissors / duct tape",
   title="The Secret to Scale Is Scissors",
   hook="From the outside, his business looked incredible. Behind the scenes, he was drowning."),
34: dict(date="Undated", conf="—", basis="Evergreen.",
   fmt=["Philosophy (short)"], topics=["Founder role","Maker vs manager"],
   idea="You can hire a CEO; you can't hire a founder. Get back in the maker's seat.",
   assets="Clean founder-vs-CEO contrast list.",
   yt=4, vid="Short, or a segment in a 'founder mode' video with #44",
   title="You Hired Yourself Into the Wrong Job",
   hook="There are 2 roles in your business, and you're in the wrong one."),
35: dict(date="2025", conf="Low", basis="Boardroom Blade ceremony.",
   fmt=["Tribute","Event recap"], topics=["Founder evolution","Leverage"],
   idea="Violinist → conductor → composer. Build something that runs without you.",
   assets="Samurai-sword award; Tony: 13 years, $20M business.",
   yt=3, vid="Much stronger with a Tony interview; otherwise a Short",
   title="Violinist, Conductor, Composer: The 3 Stages of a Founder",
   hook="'My business runs better without me.'"),
36: dict(date="2024", conf="Medium", basis="'I did that all through 2023'.",
   fmt=["Travel story (comedy)","Lesson"], topics=["Tolerations","Cutting"],
   idea="Stop chewing the gizzards. You set the menu in your business.",
   assets="Tokyo: 9 people, baby, wheelchair, 7 restaurant rejections.",
   yt=4, vid="Story video / Short",
   title="Stop Eating the Gizzards in Your Business",
   hook="I don't eat anything that used to have a job."),
37: dict(date="Mid 2026", conf="Medium", basis="Taki's '50th birthday is coming up'; uses Claude; 10 days after a Tokyo trip.",
   fmt=["Personal story (escalating comedy)","Philosophy (AI era)"], topics=["AI","Judgment","Team & hiring"],
   idea="When execution gets cheap, bad judgment gets very expensive.",
   assets="$55K AUD/night Four Seasons penthouse; 32M KRW answer; no cancellation; Amex fraud block; ended up spending $6K.",
   yt=5, vid="Story-led long-form (highest viral potential in the archive)",
   title="My Assistant Accidentally Booked a $220,000 Hotel",
   hook="For about 2 hours, I thought my marriage might be over.",
   flag="Keep the assistant anonymous. Aim the lesson at the system, not the person."),
38: dict(date="2024–25", conf="Low", basis="Team-redesign era (before the 36 → 8 cuts were finished).",
   fmt=["Confession","Update"], topics=["Team size","Artist vs mechanic"],
   idea="Simplify to multiply. Build the company around the artist, not the mechanic's model.",
   assets="The '2-screen Zoom' moment; 16 fewer people; list of changes.",
   yt=4, vid="Talking-head story; screen-recording of a 2-screen Zoom as the cold open",
   title="How Did We Become a 2-Screen Company?",
   hook="I jumped on our all-hands and felt sick. We had spilled onto a second screen."),
39: dict(date="Undated", conf="—", basis="Evergreen tutorial.",
   fmt=["Framework / how-to"], topics=["Calendar","Time"],
   idea="Compress your calendar horizontally (days) and vertically (hours). Work against the clock.",
   assets="Kraft before/after calendar grids; Taki works Tue–Fri, 8am–midday.",
   yt=5, vid="Tutorial / whiteboard walkthrough; very searchable",
   title="Spanx Your Calendar: How I Work 16 Hours a Week",
   hook="Sara Blakely made a billion dollars hiding ugly fat. Do the same to your calendar."),
40: dict(date="~Jun 2026", conf="Medium", basis="Toni's screenshot is a June campaign with targets vs '2025 sales team revenue' (so 2025 had finished).",
   fmt=["Team story","Philosophy"], topics=["Goals","Campaigns","Motivation"],
   idea="Play two games: a compass you can follow forever, and a clock (a monthly campaign) that makes you move.",
   assets="Screenshot of Toni's escalating goal list ('Now you're just being silly').",
   yt=4, vid="Story + concept; feature Toni on camera",
   title="The Compass and the Clock",
   hook="One week a month, Toni becomes insane."),
41: dict(date="Undated", conf="—", basis="Evergreen.",
   fmt=["Metaphor"], topics=["Focus","Overwhelm"],
   idea="You're a lion frozen by too many chair legs. Remove the chair.",
   assets="Annotated B&W lion-tamer photo.",
   yt=4, vid="Short (story metaphor, strong visual)",
   title="Why You're Frozen (The Lion Tamer's Chair)",
   hook="Most lion tamers died young. Clyde Beatty didn't. He brought a chair."),
42: dict(date="Undated", conf="—", basis="Post-COVID; evergreen.",
   fmt=["Philosophy","How we run it"], topics=["Day design","Events"],
   idea="Mornings are for thinking, afternoons for working and hanging out. Half days double profit and triple fun.",
   assets="Philippe Starck voicemail; half-day event format.",
   yt=3, vid="Short, or a segment inside a time/calendar video",
   title="The Calendar Mullet: Business in the Morning, Party in the Afternoon",
   hook="Call Philippe Starck's office in the morning and you get this voicemail…"),
43: dict(date="~Feb 2024", conf="High", basis="Calendar screenshot is dated Wednesday, January 31, 2024.",
   fmt=["Framework"], topics=["Strengths","Delegation","LMS"],
   idea="Build the business around your 3 magics. Dump, automate or delegate the Lesser Mortal Shit.",
   assets="Annotated calendar screenshot (Coach/Collab/Create); '1 hr of magic pays for 10 hrs of LMS'.",
   yt=5, vid="Framework + exercise; pairs with #4 for a 'strengths' playlist",
   title="Find Your 3 Magics (and Dump the Lesser Mortal Sh*t)",
   hook="There are 3 things that make time disappear for you. You're barely doing them."),
44: dict(date="Undated", conf="—", basis="Evergreen.",
   fmt=["Contrarian philosophy"], topics=["Productivity","Analog tools","Maker vs manager"],
   idea="Efficient ≠ productive. Show me the PRODUCT of your activity. Analog tools set you free.",
   assets="Studio photo (kraft bench); 3% laptop / 97% analog; Swiss vs Italians.",
   yt=4, vid="Studio tour / 'how I work' video",
   title="I Run an 8-Figure Business and Spend 3% of My Week on a Laptop",
   hook="The Swiss gave us the cuckoo clock. The Italians gave us the Renaissance."),
45: dict(date="2025", conf="Low", basis="Boardroom capped at 100, ~$5M/yr.",
   fmt=["Manifesto (refrain)"], topics=["Enough","Capping supply","Boardroom"],
   idea="Don't build the business you're supposed to want. Build the one you want.",
   assets="Boardroom: 100 cap, ~$5M/yr, 1 day a week.",
   yt=4, vid="Essay; the refrain structure suits a punchy edit",
   title="Why I Capped My $5M Program at 100 Clients",
   hook="I capped Boardroom at 100. Not because it couldn't grow."),
46: dict(date="2024–25", conf="Low", basis="Clients at '$2M a month, gunning for 3' (earlier than #2's $3M/mo).",
   fmt=["Family story","Philosophy"], topics=["Design vs default","Lifestyle"],
   idea="Everyone's driving as fast as they can. Know what you want; 92km/h is the speed of freedom.",
   assets="1965 Series II Land Rover photo; drive with the girls.",
   yt=3, vid="Mini-doc / B-roll-heavy vlog (Land Rover footage)",
   title="92km/h Is the Speed of Freedom",
   hook="Cars passed us all day, tooting and giving us the thumbs up."),
47: dict(date="~Mid-March (year unconfirmed)", conf="Medium", basis="The Facebook post shown is dated 23 Feb, and the email says '3 weeks ago'. The screenshot has no year.",
   fmt=["Vulnerable personal story"], topics=["Fear","Resistance"],
   idea="The small self keeps us in a 2-metre world. You have to take the first step.",
   assets="Facebook 'Ethan can see!' post.",
   yt=2, vid="Only with Ethan's blessing; reflective piece",
   title="(Only with family consent)",
   hook="I spoke too soon, and it's crushing me.",
   flag="Very personal. Get family consent first."),
48: dict(date="Undated", conf="—", basis="Evergreen anecdote.",
   fmt=["Anecdote","Philosophy"], topics=["Money","Wealth mindset"],
   idea="Any problem money can solve isn't a problem. Don't do mindset voodoo. Make it true.",
   assets="Dean Jackson valet moment; Dan Sullivan + Mae West quotes.",
   yt=3, vid="Short",
   title="'That's OK. We're Rich.'",
   hook="The valet charged us $50. Dean Jackson just smiled."),
49: dict(date="Mid 2026", conf="Medium", basis="Black Belt 'sold out 13 months in a row' (8 in #7, ~Feb 2026); Ethan's 26th.",
   fmt=["Personal update","Philosophy"], topics=["Priorities","Focus","Let fires burn"],
   idea="You can't fix every fire. Let some burn. Fix one thing so well it stays fixed.",
   assets="Kiri-Maree's chemo; Sydney/Noosa split; the free piano from Carol.",
   yt=3, vid="Reflective vlog. Very personal, so check with family first.",
   title="Let the Fires Burn",
   hook="Every day this season I have to choose: good husband, or good dad?",
   flag="Very personal. Check with family before publishing."),
}

TOP = [37,12,7,14,22,19,2,28,27,32,1,16,39,21,10,5]

SERIES = [
 ("Salesless: the flagship series", [12,7,16,14,18,13,15,3]),
 ("Pricing without fear", [21,19,20,22,23]),
 ("Clients who stay (Onramp / churn)", [28,27,26,25,29,30,31]),
 ("Build it by design", [2,33,32,38,45,46,34,35]),
 ("Strengths & time", [4,43,39,44,41,42,40]),
 ("Attention & demand", [10,5,8,6,9,11]),
]
